# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
files: ''

fail_fast: true

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
    - id: pyupgrade

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-merge-conflict     # Check for files that contain merge conflict strings.
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [ --autofix, --indent=4, --no-sort-keys ]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [ --profile, black ]

  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
    - id: autoflake
      args:
      - --in-place
      - --remove-all-unused-imports
      - --remove-unused-variables
      - --recursive

  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args:
      - --in-place
      - --recursive
      - --max-line-length=80

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args:
      - --ignore=E501,W503

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.61.2  # The version of cfn-lint to use
    hooks:
      - id: cfn-python-lint
        files: /template.*\.(json|yml|yaml)$
        always_run: true

  - repo: local
    hooks:
      - id: unit-tests
        name: Python Unit Tests
        entry: bash -c 'pip install -r tests/requirements.txt && pytest'
        language: python
        pass_filenames: false
        always_run: true
